name: CI - Hosting

on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main, production]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Prisma Client
        run: yarn workspace @iubizon/db generate

      - name: Check Prettier
        run: yarn pret:check

      - name: Check ESLint
        run: yarn lint

      - name: Check Types
        run: yarn type:check

      - name: Build
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
          DIRECT_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
          NEXT_PUBLIC_SUPABASE_URL: "https://dummy.supabase.co"
          NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.dummy"
          NEXT_PUBLIC_TZ: "America/Lima"
          NEXT_PUBLIC_LOCALE: "es-PE"
        run: yarn build
